### ISSUE TITLE
Exception: (standalone) XOpenDisplay: cannot open display

### ISSUE THREAD

**Issue by LISI0037** [MIT-SPARK/MiDiffusion#11]
Thank you for your great work! I'm currently trying to run this project. I'm  using a remote server environment without a graphical interface (headless). But I found the following issue when I do the data preprocessing, I run `python scripts/preprocess_data.py threed_front_livingroom`, and then:

> No GUI library found. Simple-3dviz will be running headless only.
Room type: livingroom
Traceback (most recent call last):
  File "scripts/preprocess_data.py", line 287, in <module>
    main(sys.argv[1:])
  File "scripts/preprocess_data.py", line 104, in main
    scene = scene_from_args(scene_params)
  File "/MiDiffusion/ThreedFront/threed_front/rendering.py", line 33, in scene_from_args
    ctx=moderngl.create_standalone_context(require=330)
  File "/anaconda3/envs/midiffusion/lib/python3.8/site-packages/moderngl/__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/anaconda3/envs/midiffusion/lib/python3.8/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/anaconda3/envs/midiffusion/lib/python3.8/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) XOpenDisplay: cannot open display

**Comment by LISI0037** [comment]
And someone suggest to use Xvfb to simulate a display server in this headless environment, but unfortunately, I do not have root access to the server. Installing and configuring Xvfb without root access would be quite inconvenient for me.
While I do have Mesa installed and configured for software rendering, I’m concerned about the performance implications. Do you have any advice to solve this problem?
